### ISSUE TITLE
CLI support

### ISSUE THREAD

**Issue by roccomuso** [Localize/node-google-translate#11]
Would be glad a Pull Request to bring a CLI and the possibility to install the SW as global?

My idea is to have something like:
`
$ google-translate --key <API-KEY>
`

That store the API KEY inside a json file, used to make the Calls.
Then, the possibility to use PIPES:

```
$ echo "home" | google-translate -l it
$ casa
```

again, avoiding language auto-detect:
`
$ echo "home" | google-translate -l en:it
`

Also this will be possible:

```
$ google-translate "hello world" -l it
$ ciao mondo
```

Pretty intuitive and easy. I can make it asap, just let me know if it's worth the work and if PR are welcome.

**Comment by ChrisZieba** [comment]
It's an interesting idea thanks for providing. As of right now not sure the functionality is necessary, but if it comes up again or demand for it increases we can ping you :)

**Comment by roccomuso** [comment]
I mean a lot of repo has this double usage. Through the CLI or programmatic, to be included on external modules.
