### ISSUE TITLE
Translate in not defined

### ISSUE THREAD

**Issue by sahilbabbar** [Localize/node-google-translate#20]
Hi, 

I am getting the following error: 

```
const translate = Translate();
                    ^
ReferenceError: Translate is not defined
:
:
```

The `app.js` has: 

```
var googleTranslate = require('google-translate')(my_api_key);
googleTranslate.translate('Hello', 'de', function(err, translation) {
  console.log(translation);
});
```

Where is the problem?

**Comment by CHURLZ** [comment]
print your 'err' and you might find that the API has not been enabled. The message will also include a link to enable.

**Comment by paton** [comment]
Where are you defining `Translate`? This is most likely a syntax error. Feel free to post a code example if this is still a problem.
