### ISSUE TITLE
Is this free?

### ISSUE THREAD

**Issue by erperejildo** [Localize/node-google-translate#21]
Can I use this plugin to translate content on my app for free?
I know you have to pay for Google API: https://cloud.google.com/translate/pricing

**Comment by KhaledMohamedP** [comment]
https://github.com/Localize/node-google-translate/blob/master/LICENSE

MIT license so it should be good to go (free as 🍻)

**Comment by erperejildo** [comment]
But I'm talking regarding the Google API. I read that I'd need to pay in order to use it so how can I use my API key without payment?
https://cloud.google.com/translate/pricing

**Comment by KhaledMohamedP** [comment]
@erperejildo google api is not free. If you are looking for an alternative to google, try **yandex**

**Comment by erperejildo** [comment]
Great, thanks for letting me know, I'll have a look.
So just to double check the use of this library is free BUT not the use with the Google API together. Am I wrong?

**Comment by KhaledMohamedP** [comment]
That's correct, this library won't work without a valid google API token

**Comment by erperejildo** [comment]
Perfect, thanks for the clarification

**Comment by erperejildo** [comment]
Investigating Yandex I found that I'd need to pay as Google. Do you know any other free one maybe?
https://translate.yandex.com/developers/offer/prices

**Comment by KhaledMohamedP** [comment]
@erperejildo you can get an api key from yandex free of charge. There is a limitation in how much you can translate

https://tech.yandex.com/translate/doc/dg/reference/translate-docpage/

Create a yandex account then go:
https://translate.yandex.com/developers/keys

there are multiple modules to translate via yandex in npm

**Comment by paton** [comment]
This module is free to use in your code (see license), but requires your own Google API (which is not free).

If you're translating a small amount of content (less than 2m characters), the Microsoft Translate API has a free tier, and there are npm modules for Microsoft translate as well: https://azure.microsoft.com/en-us/pricing/details/cognitive-services/translator-text-api/

If you're using the translate API for a good cause (not for profit), feel free to reach out (I work at Localize). We sometimes sponsor projects that are open source, for charity, or not-for-profit:
 (brandon@localizejs.com)

**Comment by erperejildo** [comment]
@KhaledMohamedP what I wanted to know if is possible to find other one without limitation. But anyway, need to try it out to know the real limitation. Maybe that is more than enough. Also is cheaper than Google.

@paton that sounds good. I'm not making any money with my app and just wanted to clarify if I needed to pay or not. I think if I need to pay for the translation it's because I'm using it a lot, which is totally understandable.

Cheers!
