### ISSUE TITLE
detected language not translated

### ISSUE THREAD

**Issue by gchokhonelidze** [Localize/node-google-translate#27]
If detected language is written with Latin symbols, then language is detected but not translated:

{ translatedText: ' kya hal',
detectedSourceLanguage: 'hi',
originalText: ' kya hal' }

**Comment by coltongit** [comment]
This is a limitation of the Cloud Translation API itself, and would require converting the pronunciation (which this is) into text before it can be effectively translated.

**Comment by Krunalvaghasiya** [comment]
hebrew language code generate incorrect for ISO 639-1. Currently it generate: 'iw'. But it should be :'he'

**Comment by paton** [comment]
That would be a problem with the Google Cloud Translation API itself. Not something that can be fixed here.
