### ISSUE TITLE
Got the error while building after installing this package

### ISSUE THREAD

**Issue by ngstwr** [Localize/node-google-translate#34]
These dependencies were not found:

* fs in ./node_modules/request/lib/har.js
* net in ./node_modules/forever-agent/index.js, ./node_modules/tough-cookie/lib/cookie.js and 1 other
* tls in ./node_modules/forever-agent/index.js, ./node_modules/tunnel-agent/index.js

**Comment by CodeForcer** [comment]
In React all those packages can be installed except for 'fs' which is purposely removed from React as part of create-react-app.

As it currently stands this package is unusable with React unless you use a custom installation.

Probably easier to find a different package.

**Comment by CodeForcer** [comment]
@paton might be worth updating this package officially to use Axios so it works on standard builds of frontend frameworks like React, and also to future-proof it. Requests is no longer maintained:
https://github.com/request/request/issues/3142

**Comment by paton** [comment]
@ngstwr @CodeForcer I think it's better that this module be used on the backend only. Using it on the frontend in a React app would imply you're embedding the GCP api key in your frontend javascript code, which risks someone finding your key and racking up a bill on your GCP billing account. Unless I'm missing something?
