### ISSUE TITLE
Option for setting character limit

### ISSUE THREAD

**Issue by basghar** [Localize/node-google-translate#9]
Since google translate have characters limit may be its good idea to add support for it so that it fails and do not send a request if the input is over outstanding character limit

It is not responsibility of the lib to support daily limit but to match against whatever value is provided in a call.

**Comment by paton** [comment]
How would you imagine this would work?

AFAIK, there is no way to query Google for the outstanding character limit.

Keeping track of the number of characters translated in the last X hours in the library also wouldn't be very reliable (if the server restarts the count would go back to 0, and it wouldn't be possible to keep track of character count if you use the library on multiple servers).

**Comment by basghar** [comment]
No I am talking about very simple character limit. 

so translate(jso, {maxCharCount: 100000});

**Comment by paton** [comment]
Hm, I don't quite see the use case for wanting to limit the max input length on the library level. It sounds like you want to block your application from translating strings longer than X characters? This might be better handled in the application code.

**Comment by basghar** [comment]
good point.
